title: My awesome title
author: GitHub User (mrtbts)
email: meepooh2009@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _conresults) and in your feed.xml site description.
fig.yml. It will appear in your document head meta (for
  Google search 
# social links
twitter_username: i do not have # DO NOT include the @ character, or else the build will fail!
github_username:  scratchusernamemrtbts # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
